### PR TITLE
TC-DeleteTag#15

### PR DESCRIPTION
**Pull request by Trey-Chambers**
# Description

Added the ability to delete any unwanted tags

Trello: [Ticket 15](https://trello.com/c/gSQOToWR/15-15-delete-a-tag)
Branch: TC-DeleteTag#15

# Testing Instructions

1.`git add` and `git commit` whatever you're working on on your branch 
2. `git checkout main`
3.`git fetch --a`
4.`git checkout <TC-DeleteTag#15>`
5.If you don't see the most recent version of my files, `git pull origin <TC-DeleteTag#15>`
6.If you haven't created the Tabloid MVC database, please do so.
7. Use this data to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-bit-o-honeys/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
8.  Use this to seed the database : [SQL SEED DATA](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
9. Click the execute with debugger solid green button to launch the app
10. In browser, please go to `Login` on the nav bar and log in with this email: `admin@example.com`
11. User should be redirected to `Home` page
12. From the home page select `Tags` on the nav bar
13. User should be routed to the `/Tag` page
14. User should see a list of Tags in alphabetical order (_C#_, _Cyclopean Terrors_, _Family_, _Javascript_)
15.  User should click the create tag button
16. User will be redirected to a new page to enter  the name of a new tag
17. Enter new tag name and click the create button
18. User should be redirected back to list of tags where they will see the new tag in the list of tags
19. On the right side of the tag you just created user should see the `Edit | Details | Delete` buttons. Click the `Delete` button.
20. User should be redirected to a page that asks "Are you sure you want to delete `<tag.Name>`? Under that question Users should see the `<tag.Id>` and `<tag.Name>` of the tag they selected to delete
21. User should press the red delete button
22. User should be redirected back to the list of tags minus the tag the user deleted

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by robert-brunner — APPROVED** [review]
I was able to delete tags.  Code works as expected.

**Comment by sarahebrooks12** [comment]
Add instructions for creating a tag and then deleting it. We don't want to delete seed data 🐮 🔔

**Review by jacobjjude — APPROVED** [review]
🌟 Tested. Created a Tag, deleted it.

**Comment by sarahebrooks12** [comment]
Testing instructions look good --- get 2 testing approvals before merging 👼

**Pull request merged**
