### PR TITLE
Jj edit a category#12 take two

### PR DESCRIPTION
**Pull request by jacobjjude**
# Description

Added an editing function to the categories list.

[Trello Card](https://trello.com/c/u4sX9BOp)

# Testing Instructions

# Testing Instructions

1. `git add` and `git commit` whatever you're working on on your branch
2. `git checkout main`
3. `git fetch --a`
4. `git checkout <JJ-EditACategory#12TakeTwo>`
5. If you don't see the most recent version of my files, `git pull origin <JJ-EditACategory#12TakeTwo>`
6. If you haven't created the Tabloid MVC database, please do so.
7. Use this data to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
8. Use this to seed the database : [SQL SEED DATA](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
9. Click the execute with debugger solid green button to launch the app
10. Log into the website using “admin@example.com” if greeted with a login page
11. From the home page, click the “CATEGORY MANAGEMENT” option in the navbar
12. Verify that the URL ends in "/Category"
## Categories to be seen, in order

- Close Magic
- Cooking
- Cthulhu Sightings
- Entertainment
- History
- Home and Garden
- Improv
- Movies
- Music
- Politics
- Regrets
- Science
- Technology
13. You should be redirected to a page with all available categories listed. Click the “Edit” button on any of the table rows.
14. Verify that the URL ends in "/Category/Edit/[Id # of whatever item you selected]"
15. You should see a page with A text box containing text of the Category you selected.
16. You can edit the text if you wish and hit save to save your changes.
17. If you hit "back to list" it will take you back to the category list.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
Testing instructions look good --- get 2 testing approvals before merging 👼

**Review by robert-brunner — APPROVED** [review]
Works

**Review by CaraNetzer — APPROVED** [review]
Tested and working!

**Review by Trey-Chambers — APPROVED** [review]
Tested and working

**Pull request merged**
