### PR TITLE
TC-CreateTag#14

### PR DESCRIPTION
**Pull request by Trey-Chambers**
# Description

Added the ability for users to create a new tag
Trello: [Card#14](https://trello.com/c/rA5gnsXp/14-14-create-a-tag)
Branch: TC-CreateTag#14

# Testing Instructions

1.`git add` and `git commit` whatever you're working on on your branch 
2. `git checkout main`
3.`git fetch --a`
4.`git checkout <TC-ViewAllTags#13>`
5.If you don't see the most recent version of my files, `git pull origin <TC-ViewAllTags#13>`
6.If you haven't created the Tabloid MVC database, please do so.
7. Use this data to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-bit-o-honeys/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
8.  Use this to seed the database : [SQL SEED DATA](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
9. Click the execute with debugger solid green button to launch the app
10. In browser, please go to `Login` on the nav bar and log in with this email: `admin@example.com`
11. User should be redirected to `Home` page
12. From the home page select `Tags` on the nav bar
13. User should be routed to the `/Tag` page
14. User should see a list of Tags in alphabetical order (_C#_, _Cyclopean Terrors_, _Family_, _Javascript_) as well as a `Create Tag` button.
15. Click the `Create Tag` button
16. User Should be transported to the `Tag/Create` page where they will be able to create a  new tag
17. Enter name of new `tag` in the blank space
18. Press the `create` button
19. User should be transported back to the list of tags
20. User should see their newly created tag in alphabetical order

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Please add the tags in alphabetical order on the testing instructions so we can verify that we are getting the correct information from the database.

**Review by jacobjjude — APPROVED** [review]
🌟 Tested, works as intended.

**Review by sarahebrooks12 — COMMENTED** [review]
Testing instructions are good. Please get 2 testing approvals before merging

**Review by sarahebrooks12 — APPROVED** [review]

**Review by CaraNetzer — APPROVED** [review]
Tested and working!

**Pull request merged**
