### PR TITLE
#9 View All Categories

### PR DESCRIPTION
**Pull request by jacobjjude**
# Description

I have added the "Category Management" button to the task bar, which should redirect admin users to a page where they can view (and only view for the time being) all categories listed in alphabetical order. On the category management page, users should be able to view the Id, Name, a list of "Edit/Details/Delete", and a Create New button for Categories.

Trello card: https://trello.com/c/K13uFq8c

# Testing Instructions

1) `git add` and `git commit` whatever you are working on in your branch.
2) `git checkout main`, or `git clone https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls.git` if you need the code.
3) `git fetch -a`
4) `git checkout <JJ-ViewAllCategories#22>`
5) If you don't see the most recent version of my files, `git pull origin <JJ-ViewAllCategories#22>`
6) In Visual Studio (if you have not created the TabloidMVC database), 
- Open the SQL Server Object Explorer
- In the Server Object Explorer window, find and right-click the SQLEXPRESS tab.
- Click new query, in the window that pops up, copy the code from the following files and click play to run the queries.
- Fill the colums and rows: https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/01_TabloidMVC_Create_DB.sql
- Seed data: https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/02_TabloidMVC_Seed_Data.sql

7) Open Visual Studio, click "Open a project or solution", find and click "TabloidMVC.sln"
8) Run the program through the debugger
9) If needed, log in using "admin@example.com"
10) After logging in, click the "CATEGORY MANAGEMENT" option in the NavBar
## Categories that should be seen (in order):
- Close Magic
- Cooking
- Cthulhu Sightings
- Entertainment
- History
- Home and Garden
- Improv
- Movies
- Music
- Politics
- Regrets
- Science
- Technology

11) Verify that the URL ends in "/Category", that all the categories are listed on the page, and that they are in alphabetical order.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Tommy-Spurlock** [comment]
Not bad but needs to include more detail on how to properly test. Should include:
1. SQL script and instructions on how to test. 
2. instructions on how to navigate to your branch 
--------------------------------

Better, however I'd still like to see more descriptive and detailed set up instructions

**Review by CaraNetzer — APPROVED** [review]
Tested and working!

**Comment by Tommy-Spurlock** [comment]
Much better. Merge it!

**Review by Trey-Chambers — APPROVED** [review]
Tested and working as intended

**Pull request merged**
